# This GitHub Action builds the Docker image Promptfoo,
# runs the Docker container, performs a health check to ensure the application
# is running correctly, and then publishes the image to GitHub Container Registry
# if all checks pass. This action is triggered on release creation, workflow dispatch,
# pull requests to main that modify the Dockerfile, and pushes to main.

name: Test and Publish Multi-arch Docker Image
run-name: |
  ${{ github.event_name == 'release' && 'Release' ||
      github.event_name == 'workflow_dispatch' && 'Manual' ||
      github.event_name == 'pull_request' && 'PR' ||
      'Push' }}
  Docker build for ${{ github.ref_name }}
  ${{ github.event_name == 'pull_request' && format('(PR #{0})', github.event.number) || '' }}
  by @${{ github.actor }}

on:
  pull_request:
    branches:
      - main  # Adjust to match the branch your PR targets

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  PROMPTFOO_REMOTE_API_BASE_URL: 'http://localhost:3400'
  PROMPTFOO_REMOTE_APP_BASE_URL: 'http://localhost:3400'

permissions:
  contents: read
  packages: write

jobs:
  test-and-publish:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image for testing
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          load: true
          tags: local-test-image:latest
          platforms: linux/amd64

      - name: Run Docker container for testing
        run: docker run -d --name promptfoo-container -p 3400:3000 local-test-image:latest

      - name: Verify Python and promptfoo
        run: |
          echo "Checking Python version:"
          docker exec promptfoo-container python --version
          if [ $? -ne 0 ]; then
            echo "Python check failed"
            exit 1
          fi

          echo "Checking promptfoo version:"
          docker exec promptfoo-container promptfoo --version
          if [ $? -ne 0 ]; then
            echo "promptfoo check failed"
            exit 1
          fi

      - name: Run health check
        run: |
          # Loop to check if the server is up
          for i in {1..10}; do
            if curl -f http://localhost:3400/health; then
              echo -e "\nHealth check passed"
              HEALTH_CHECK_PASS=true
              break
            else
              echo "Health check failed, retrying in 2 seconds..."
              sleep 2
            fi
          done

          # If health check did not pass after retries, exit with an error
          if [ -z "$HEALTH_CHECK_PASS" ]; then
            echo -e "\nHealth check failed after multiple attempts" >&2
            exit 1
          fi
      - name: run promptfoo eval
        id: eval
        run: |
          npm install
          npm run local -- eval -c .github/promptfooconfig.yml --share

      - name: Extract evalId and make curl request
        run: |
          response=$(curl -s http://localhost:3400/api/results)
          echo "Response: $response"

          # Use jq to extract the array length
          count=$(echo "$response" | jq '.data | length')
          echo "Array Length: $count"

          # Check if the count is exactly 1
          if [ "$count" -ne 1 ]; then
            echo "Error: Expected 1 entry, but got $count"
            exit 1  # Fail the job if count is not 1
          fi

      - name: Stop and remove Docker container
        if: always()
        run: |
          docker stop promptfoo-container
          docker rm promptfoo-container

