# .github/workflows/pr-trigger.yml
name: PR Trigger Action

on:
  pull_request:
    branches:
      - main  # Adjust to match the branch your PR targets

jobs:
  eval:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: run promptfoo eval
        id: eval
        run: |
          npm install
          npm run local -- eval -c .github/promptfooconfig.yml --share

      - name: Extract evalId and make curl request
        run: |
         # Extract evalId from the log
         eval_id=$(grep -oP 'evalId=\K[\w-]+' <(echo "${{ join(steps.eval.outputs.*, ' ') }}"))
    
         # Check if evalId was found
         if [ -z "$eval_id" ]; then
           echo "Failed to extract evalId"
           exit 1
         fi
    
         echo "Extracted evalId: $eval_id"
